USE IG_CLONE;
SELECT * FROM USERS;

/* ANS 1 */
SELECT * FROM USERS ORDER BY CREATED_AT DESC LIMIT 5;

SELECT * FROM USERS;
SELECT * FROM PHOTOS;

-- ANS 2
SELECT A.USERNAME, COUNT(B.IMAGE_URL) AS POSTS
FROM USERS AS A
LEFT JOIN PHOTOS AS B
ON A.ID = B.USER_ID
GROUP BY A.USERNAME HAVING COUNT(B.IMAGE_URL) = 0;

-- ANS 3
SELECT * FROM PHOTOS;
SELECT * FROM LIKES;
SELECT A.USER_ID, B.USERNAME, C.PHOTO_ID, COUNT(C.USER_ID) AS NumberOfLikes
FROM LIKES AS C JOIN PHOTOS AS A JOIN USERS AS B
ON B.ID = A.USER_ID AND A.ID = C.PHOTO_ID
WHERE C.USER_ID GROUP BY C.PHOTO_ID ORDER BY NumberOfLikes DESC LIMIT 1;


-- ANS 4
select * from tags;
SELECT * FROM PHOTO_TAGS;
SELECT A.TAG_NAME, COUNT(B.TAG_ID) AS TimesUsed
FROM TAGS AS A JOIN PHOTO_TAGS AS B
ON A.ID = B.TAG_ID
GROUP BY B.TAG_ID ORDER BY TimesUsed DESC LIMIT 5;

-- ANS 5
SELECT * FROM USERS;
SELECT DAYOFWEEK(CREATED_AT) AS DayOfWeek, COUNT(ID) AS Accounts FROM USERS 
GROUP BY DayOfWeek ORDER BY Accounts DESC;

-- ANS 6
SELECT * FROM PHOTOS;
SELECT USER_ID AS Users, COUNT(ID) AS NumberOfPosts FROM PHOTOS GROUP BY USER_ID;

-- ANS 7
SELECT A.USERNAME, B.USER_ID, COUNT(B.CREATED_AT) AS NumberOfPhotosLiked
FROM USERS AS A JOIN LIKES AS B
ON A.ID = B.USER_ID
GROUP BY B.USER_ID HAVING NumberOfPhotosLiked = 257;
